/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Eduardo Arturo Gutiérrez Hernández
 */
public class MenuPrincipal extends javax.swing.JFrame {

    //Declaración de menus para la navegación entre paginas.
    private MenuTareasPendientes FormMenuTareasPendientes;
    private InicioDeSesion FormInicioDeSesion;
    private MiCuenta FormMiCuenta;
    private Cocinas FormCocinas;
    private Escaleras FormEscaleras;
    private Oficinas FormOficinas;
    private Otros FormOtros;
    private Pasillos FormPasillos;
    private PlantasBajas FormPlantasBajas;
    private Salones FormSalones;
    private Sanitarios FormSanitarios;
    private Consultas FormRegistros;
    
    //Objetos para las imagenes
    private ImageIcon imagen;
    private Icon icono;
    
    public MenuPrincipal() {
        initComponents();
        // Obtener el tamaño de la pantalla
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

        // Establecer el tamaño del JFrame al tamaño de la pantalla
        this.setSize(screenSize.width, screenSize.height);

        // Opcional: Establecer la posición del JFrame en la esquina superior izquierda
        this.setLocation(0, 0);
        
        //
        this.setLocationRelativeTo(this);
        //this.pintarImagen(this.lblLogoUtj, "src/Imagenes/pbuno.png");
        this.pintarImagen(this.lblBarraVerde, "src/Imagenes/verdeUtj.png");


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        pnlBlanco = new javax.swing.JPanel();
        lblLogoUtj = new javax.swing.JLabel();
        lblAreaDeMantenimiento = new javax.swing.JLabel();
        lblBarraVerde = new javax.swing.JLabel();
        btnEscaleras = new javax.swing.JButton();
        btnOficinas = new javax.swing.JButton();
        btnCocinas = new javax.swing.JButton();
        btnSalones = new javax.swing.JButton();
        btnPlantasBajas = new javax.swing.JButton();
        btnPasillos = new javax.swing.JButton();
        btnOtros = new javax.swing.JButton();
        lblLogoAreaDeMantenimiento = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();
        btnRegistros = new javax.swing.JButton();
        btnPendientes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSanitarios = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setResizable(false);

        pnlBlanco.setBackground(new java.awt.Color(255, 255, 255));
        pnlBlanco.setMinimumSize(new java.awt.Dimension(0, 0));
        pnlBlanco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogoUtj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoUTJ.png"))); // NOI18N
        pnlBlanco.add(lblLogoUtj, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 10, -1, -1));

        lblAreaDeMantenimiento.setFont(new java.awt.Font("Calibri", 1, 72)); // NOI18N
        lblAreaDeMantenimiento.setForeground(new java.awt.Color(255, 255, 255));
        lblAreaDeMantenimiento.setText("Área de mantenimiento CCD");
        pnlBlanco.add(lblAreaDeMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 870, 110));

        lblBarraVerde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verdeUtj.png"))); // NOI18N
        pnlBlanco.add(lblBarraVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1950, 130));

        btnEscaleras.setBackground(new java.awt.Color(255, 255, 255));
        btnEscaleras.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        btnEscaleras.setForeground(new java.awt.Color(0, 0, 0));
        btnEscaleras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/escaleras.png"))); // NOI18N
        btnEscaleras.setText("  Escaleras");
        btnEscaleras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscalerasActionPerformed(evt);
            }
        });
        pnlBlanco.add(btnEscaleras, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 390, 140));

        btnOficinas.setBackground(new java.awt.Color(255, 255, 255));
        btnOficinas.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        btnOficinas.setForeground(new java.awt.Color(0, 0, 0));
        btnOficinas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/oficina.png"))); // NOI18N
        btnOficinas.setText("  Oficinas");
        btnOficinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOficinasActionPerformed(evt);
            }
        });
        pnlBlanco.add(btnOficinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 390, 140));

        btnCocinas.setBackground(new java.awt.Color(255, 255, 255));
        btnCocinas.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        btnCocinas.setForeground(new java.awt.Color(0, 0, 0));
        btnCocinas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cocina.png"))); // NOI18N
        btnCocinas.setText("  Cocinas");
        btnCocinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCocinasActionPerformed(evt);
            }
        });
        pnlBlanco.add(btnCocinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 640, 390, 140));

        btnSalones.setBackground(new java.awt.Color(255, 255, 255));
        btnSalones.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        btnSalones.setForeground(new java.awt.Color(0, 0, 0));
        btnSalones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salon-de-clases.png"))); // NOI18N
        btnSalones.setText("  Salones");
        btnSalones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalonesActionPerformed(evt);
            }
        });
        pnlBlanco.add(btnSalones, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 320, 400, 140));

        btnPlantasBajas.setBackground(new java.awt.Color(255, 255, 255));
        btnPlantasBajas.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        btnPlantasBajas.setForeground(new java.awt.Color(0, 0, 0));
        btnPlantasBajas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/planta-baja.png"))); // NOI18N
        btnPlantasBajas.setText("  Plantas bajas");
        btnPlantasBajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlantasBajasActionPerformed(evt);
            }
        });
        pnlBlanco.add(btnPlantasBajas, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 480, 400, 140));

        btnPasillos.setBackground(new java.awt.Color(255, 255, 255));
        btnPasillos.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        btnPasillos.setForeground(new java.awt.Color(0, 0, 0));
        btnPasillos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pasillo.png"))); // NOI18N
        btnPasillos.setText("  Pasillos");
        btnPasillos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasillosActionPerformed(evt);
            }
        });
        pnlBlanco.add(btnPasillos, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 640, 400, 140));

        btnOtros.setBackground(new java.awt.Color(255, 255, 255));
        btnOtros.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        btnOtros.setForeground(new java.awt.Color(0, 0, 0));
        btnOtros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edificio.png"))); // NOI18N
        btnOtros.setText("  Otros");
        btnOtros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtrosActionPerformed(evt);
            }
        });
        pnlBlanco.add(btnOtros, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 320, 390, 140));

        lblLogoAreaDeMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/area-restringida (1).png"))); // NOI18N
        pnlBlanco.add(lblLogoAreaDeMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(238, 248, 247));

        btnVolver.setBackground(new java.awt.Color(255, 255, 255));
        btnVolver.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(153, 0, 0));
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar-sesion (1).png"))); // NOI18N
        btnVolver.setText("Cerrar sesión\n");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnRegistros.setBackground(new java.awt.Color(0, 102, 102));
        btnRegistros.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        btnRegistros.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carpeta.png"))); // NOI18N
        btnRegistros.setText("  Registros");
        btnRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrosActionPerformed(evt);
            }
        });

        btnPendientes.setBackground(new java.awt.Color(255, 255, 255));
        btnPendientes.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        btnPendientes.setForeground(new java.awt.Color(0, 0, 0));
        btnPendientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pendiente.png"))); // NOI18N
        btnPendientes.setText("  Pendientes");
        btnPendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPendientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(btnRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addComponent(btnPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 287, Short.MAX_VALUE)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(270, 270, 270))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 70, Short.MAX_VALUE))
        );

        pnlBlanco.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 805, 1960, 210));

        jLabel1.setText("jLabel1");
        pnlBlanco.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        btnSanitarios.setBackground(new java.awt.Color(255, 255, 255));
        btnSanitarios.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        btnSanitarios.setForeground(new java.awt.Color(0, 0, 0));
        btnSanitarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bano.png"))); // NOI18N
        btnSanitarios.setText("  Sanitarios");
        btnSanitarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSanitariosActionPerformed(evt);
            }
        });
        pnlBlanco.add(btnSanitarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 480, 390, 140));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user.png"))); // NOI18N
        jButton3.setText("  Mi cuenta");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        pnlBlanco.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 640, 390, 140));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1970, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 142, Short.MAX_VALUE)
        );

        pnlBlanco.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 124, 1970, 142));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlBlanco, javax.swing.GroupLayout.DEFAULT_SIZE, 1966, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBlanco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1016, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEscalerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscalerasActionPerformed
        //Cierra el frame anterior, inicializa el frame a invocar y lo muesta.
        dispose();
        FormEscaleras = new Escaleras();
        FormEscaleras.setVisible(true);
    }//GEN-LAST:event_btnEscalerasActionPerformed

    private void btnSalonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalonesActionPerformed
        //Cierra el frame anterior, inicializa el frame a invocar y lo muesta.
        dispose();
        FormSalones = new Salones();
        FormSalones.setVisible(true);
    }//GEN-LAST:event_btnSalonesActionPerformed

    private void btnCocinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCocinasActionPerformed
        dispose();
        FormCocinas = new Cocinas();
        FormCocinas.setVisible(true);
    }//GEN-LAST:event_btnCocinasActionPerformed

    private void btnOficinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOficinasActionPerformed
        dispose();
        FormOficinas = new Oficinas();
        FormOficinas.setVisible(true);
    }//GEN-LAST:event_btnOficinasActionPerformed

    private void btnPlantasBajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlantasBajasActionPerformed
        dispose();
        FormPlantasBajas = new PlantasBajas();
        FormPlantasBajas.setVisible(true);
    }//GEN-LAST:event_btnPlantasBajasActionPerformed

    private void btnPasillosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasillosActionPerformed
        dispose();
        FormPasillos = new Pasillos();
        FormPasillos.setVisible(true);
    }//GEN-LAST:event_btnPasillosActionPerformed

    private void btnOtrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtrosActionPerformed
        dispose();
        FormOtros = new Otros();
        FormOtros.setVisible(true);
    }//GEN-LAST:event_btnOtrosActionPerformed

    private void btnSanitariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanitariosActionPerformed
        dispose();
        FormSanitarios = new Sanitarios();
        FormSanitarios.setVisible(true);
    }//GEN-LAST:event_btnSanitariosActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
        FormMiCuenta = new MiCuenta();
        FormMiCuenta.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrosActionPerformed
        dispose();
        FormRegistros = new Consultas();
        FormRegistros.setVisible(true);
    }//GEN-LAST:event_btnRegistrosActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        //Cierra el frame anterior, inicializa el frame a invocar y lo muesta.
        dispose();
        FormInicioDeSesion = new InicioDeSesion();
        FormInicioDeSesion.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnPendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPendientesActionPerformed
        dispose();
        FormMenuTareasPendientes = new MenuTareasPendientes();
        FormMenuTareasPendientes.setVisible(true);
    }//GEN-LAST:event_btnPendientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    //Metodo para cambiar de tamaño las imagenes
        private void pintarImagen(JLabel lblBarraVerde, String root){
            this.imagen = new ImageIcon(root);
            this.icono = new ImageIcon(
                    this.imagen.getImage().getScaledInstance(
                            lblBarraVerde.getWidth(), 
                            lblBarraVerde.getHeight(), 
                            Image.SCALE_DEFAULT)
            );
            lblBarraVerde.setIcon(this.icono);
            this.repaint();
        }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCocinas;
    private javax.swing.JButton btnEscaleras;
    private javax.swing.JButton btnOficinas;
    private javax.swing.JButton btnOtros;
    private javax.swing.JButton btnPasillos;
    private javax.swing.JButton btnPendientes;
    private javax.swing.JButton btnPlantasBajas;
    private javax.swing.JButton btnRegistros;
    private javax.swing.JButton btnSalones;
    private javax.swing.JButton btnSanitarios;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAreaDeMantenimiento;
    private javax.swing.JLabel lblBarraVerde;
    private javax.swing.JLabel lblLogoAreaDeMantenimiento;
    private javax.swing.JLabel lblLogoUtj;
    private javax.swing.JPanel pnlBlanco;
    // End of variables declaration//GEN-END:variables

   
}
