/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Eduardo Arturo Gutiérrez Hernández
 */
public class MenuTareasPendientes extends javax.swing.JFrame {

    //Declaración de menus para la navegación entre paginas.
    private MenuPrincipal FormMenuPrincipal;
    private TareasPendientes FormTareasPendientes;
    private ConsultarTareasPendientes FormConsultarTareasPendientes;
    
    //Objetos para las imagenes
    private ImageIcon imagen;
    private Icon icono;
    
    public MenuTareasPendientes() {
        initComponents();
        
        // Obtener el tamaño de la pantalla
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

        // Establecer el tamaño del JFrame al tamaño de la pantalla
        this.setSize(screenSize.width, screenSize.height);

        // Opcional: Establecer la posición del JFrame en la esquina superior izquierda
        this.setLocation(0, 0);
        
        //
        this.setLocationRelativeTo(this);
        //this.pintarImagen(this.lblLogoUtj, "src/Imagenes/pbuno.png");
        this.pintarImagen(this.lblBarraVerde, "src/Imagenes/verdeUtj.png");
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblAreaDeMantenimiento = new javax.swing.JLabel();
        lblBarraVerde = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblLogoAreaDeMantenimiento = new javax.swing.JLabel();
        lblLogoUtj = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnAgregarNuevaTarea = new javax.swing.JButton();
        btnConsultarTareasPendientes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAreaDeMantenimiento.setFont(new java.awt.Font("Calibri", 1, 72)); // NOI18N
        lblAreaDeMantenimiento.setForeground(new java.awt.Color(255, 255, 255));
        lblAreaDeMantenimiento.setText("Menú tareas pendientes");
        jPanel1.add(lblAreaDeMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 870, 110));

        lblBarraVerde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verdeUtj.png"))); // NOI18N
        jPanel1.add(lblBarraVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1950, 130));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1970, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 142, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 124, 1970, 142));

        lblLogoAreaDeMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/area-restringida (1).png"))); // NOI18N
        jPanel1.add(lblLogoAreaDeMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, -1, -1));

        lblLogoUtj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoUTJ.png"))); // NOI18N
        jPanel1.add(lblLogoUtj, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 10, -1, -1));

        btnVolver.setBackground(new java.awt.Color(255, 255, 255));
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(1690, 870, 121, 98));

        btnAgregarNuevaTarea.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregarNuevaTarea.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        btnAgregarNuevaTarea.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregarNuevaTarea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar-tarea.png"))); // NOI18N
        btnAgregarNuevaTarea.setText("  Agregar nueva tarea");
        btnAgregarNuevaTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarNuevaTareaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarNuevaTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 410, 580, 170));

        btnConsultarTareasPendientes.setBackground(new java.awt.Color(255, 255, 255));
        btnConsultarTareasPendientes.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        btnConsultarTareasPendientes.setForeground(new java.awt.Color(0, 0, 0));
        btnConsultarTareasPendientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lista.png"))); // NOI18N
        btnConsultarTareasPendientes.setText("Consultar tareas pendientes");
        btnConsultarTareasPendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarTareasPendientesActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultarTareasPendientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 670, 590, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1968, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1016, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        dispose();
        FormMenuPrincipal = new MenuPrincipal();
        FormMenuPrincipal.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnAgregarNuevaTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarNuevaTareaActionPerformed
        dispose();
        FormTareasPendientes = new TareasPendientes();
        FormTareasPendientes.setVisible(true);
    }//GEN-LAST:event_btnAgregarNuevaTareaActionPerformed

    private void btnConsultarTareasPendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarTareasPendientesActionPerformed
        dispose();
        FormConsultarTareasPendientes = new ConsultarTareasPendientes();
        FormConsultarTareasPendientes.setVisible(true);
    }//GEN-LAST:event_btnConsultarTareasPendientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuTareasPendientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuTareasPendientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuTareasPendientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuTareasPendientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuTareasPendientes().setVisible(true);
            }
        });
    }
    
    //Metodo para cambiar de tamaño las imagenes
        private void pintarImagen(JLabel lblBarraVerde, String root){
            this.imagen = new ImageIcon(root);
            this.icono = new ImageIcon(
                    this.imagen.getImage().getScaledInstance(
                            lblBarraVerde.getWidth(), 
                            lblBarraVerde.getHeight(), 
                            Image.SCALE_DEFAULT)
            );
            lblBarraVerde.setIcon(this.icono);
            this.repaint();
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarNuevaTarea;
    private javax.swing.JButton btnConsultarTareasPendientes;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAreaDeMantenimiento;
    private javax.swing.JLabel lblBarraVerde;
    private javax.swing.JLabel lblLogoAreaDeMantenimiento;
    private javax.swing.JLabel lblLogoUtj;
    // End of variables declaration//GEN-END:variables
}
