/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

import BackEnd.Usuario;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import FrontEnd.InicioDeSesion;
import javax.swing.JOptionPane;

/**
 *
 * @author Eduardo Arturo Gutiérrez Hernández
 */
public class MiCuenta extends javax.swing.JFrame {
    
    // Objeto Usuario
    Usuario usuario = new Usuario();
    
    
    //Objetos para las imagenes
    private ImageIcon imagen;
    private Icon icono;

    //JFrames
    private MenuPrincipal FormMenuPrincipal;
    
    public MiCuenta() {
        usuario.busquedausuario(InicioDeSesion.correo);
        //System.out.println(InicioDeSesion.nombre);
        initComponents();
        System.out.println(InicioDeSesion.correo);
        
        // Obtener el tamaño de la pantalla
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

        // Establecer el tamaño del JFrame al tamaño de la pantalla
        this.setSize(screenSize.width, screenSize.height);

        // Opcional: Establecer la posición del JFrame en la esquina superior izquierda
        this.setLocation(0, 0);
        
        //Ajustando el tamaño de las imagenes
        this.setLocationRelativeTo(this);
        this.pintarImagen(this.lblBarraVerde, "src/Imagenes/verdeUtj.png");
        this.pintarImagen(lblFondoAzul, "src/Imagenes/verdeUtj_1.png");
        this.pintarImagen(lblFondoMorado, "src/Imagenes/fondoMorado.png");
        
        
        
        // Mostrar la información del usuario en los JTextField
        txtId.setText(String.valueOf(usuario.getId()));
        txtNombre.setText(usuario.getNombre());
        txtApellidos.setText(usuario.getApellidos());
        txtCorreo.setText(InicioDeSesion.correo);
        txtContresenia.setText(usuario.getContrasenia()); // Opcional
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipalBlanco = new javax.swing.JPanel();
        lblLogoUtj = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblContrasenia = new javax.swing.JLabel();
        txtContresenia = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        lblBarraVerde = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        lblNombre1 = new javax.swing.JLabel();
        lblFondoAzul = new javax.swing.JLabel();
        lblFondoMorado = new javax.swing.JLabel();
        lblLogoAreaDeMantenimiento = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1630, 564));

        pnlPrincipalBlanco.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipalBlanco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogoUtj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoUTJ.png"))); // NOI18N
        pnlPrincipalBlanco.add(lblLogoUtj, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 72)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mi cuenta");
        pnlPrincipalBlanco.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 182, -1, -1));

        lblNombre.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(0, 0, 51));
        lblNombre.setText("Nombre:");
        pnlPrincipalBlanco.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 456, -1, -1));

        lblApellidos.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        lblApellidos.setForeground(new java.awt.Color(0, 0, 51));
        lblApellidos.setText("Apellidos:");
        pnlPrincipalBlanco.add(lblApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 516, -1, -1));

        lblCorreo.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(0, 0, 51));
        lblCorreo.setText("Correo:");
        pnlPrincipalBlanco.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 578, -1, -1));

        lblContrasenia.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        lblContrasenia.setForeground(new java.awt.Color(0, 0, 51));
        lblContrasenia.setText("Contraseña:");
        pnlPrincipalBlanco.add(lblContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 636, -1, -1));

        txtContresenia.setBackground(new java.awt.Color(255, 255, 255));
        txtContresenia.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        txtContresenia.setForeground(new java.awt.Color(0, 0, 51));
        pnlPrincipalBlanco.add(txtContresenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 630, 470, -1));

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 0, 51));
        txtNombre.setEnabled(false);
        pnlPrincipalBlanco.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 450, 470, -1));

        txtCorreo.setBackground(new java.awt.Color(255, 255, 255));
        txtCorreo.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(0, 0, 51));
        txtCorreo.setEnabled(false);
        pnlPrincipalBlanco.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 570, 470, -1));

        txtApellidos.setBackground(new java.awt.Color(255, 255, 255));
        txtApellidos.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        txtApellidos.setForeground(new java.awt.Color(0, 0, 51));
        txtApellidos.setEnabled(false);
        pnlPrincipalBlanco.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 510, 470, -1));

        btnGuardar.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardar.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(0, 0, 51));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        pnlPrincipalBlanco.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 730, 190, 80));

        btnVolver.setBackground(new java.awt.Color(255, 255, 255));
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        pnlPrincipalBlanco.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(1560, 870, 120, 90));

        lblBarraVerde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verdeUtj.png"))); // NOI18N
        pnlPrincipalBlanco.add(lblBarraVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1970, 130));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1970, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 142, Short.MAX_VALUE)
        );

        pnlPrincipalBlanco.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 144, 1970, 142));

        txtId.setBackground(new java.awt.Color(255, 255, 255));
        txtId.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        txtId.setForeground(new java.awt.Color(0, 0, 51));
        txtId.setEnabled(false);
        pnlPrincipalBlanco.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 390, 470, -1));

        lblNombre1.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        lblNombre1.setForeground(new java.awt.Color(0, 0, 51));
        lblNombre1.setText("Id:");
        pnlPrincipalBlanco.add(lblNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(746, 397, -1, -1));

        lblFondoAzul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/azulfondo.png"))); // NOI18N
        lblFondoAzul.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        pnlPrincipalBlanco.add(lblFondoAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 970, 490));

        lblFondoMorado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoMorado.png"))); // NOI18N
        lblFondoMorado.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        pnlPrincipalBlanco.add(lblFondoMorado, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 1010, 530));

        lblLogoAreaDeMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/area-restringida (1).png"))); // NOI18N
        pnlPrincipalBlanco.add(lblLogoAreaDeMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipalBlanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPrincipalBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, 1223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        //usuario.ModificarUsuario(WIDTH, nuevaContrasenia);
        //System.out.println(""+usuario.getContrasenia());
        // Obtener el id del usuario y la nueva contraseña desde los campos de texto, por ejemplo
    int idUsuario = Integer.parseInt(txtId.getText()); // Asegúrate de tener un campo de texto para el ID del usuario
    String nuevaContrasenia = txtContresenia.getText(); // Campo de texto para la nueva contraseña

    // Crear una instancia de UsuarioDAO
    Usuario usuarioDAO = new Usuario();
    
    // Llamar al método ModificarUsuario
    String resultado = usuarioDAO.ModificarUsuario(idUsuario, nuevaContrasenia);
    
    // Mostrar el resultado en la consola o en una etiqueta de la interfaz
    JOptionPane.showMessageDialog(null, "Contraseña actualizada exitosamente.");
    txtContresenia.setText(nuevaContrasenia);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        dispose();
        FormMenuPrincipal = new MenuPrincipal();
        FormMenuPrincipal.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MiCuenta().setVisible(true);
            }
        });
    }
    
    //Metodo para cambiar de tamaño las imagenes
        private void pintarImagen(JLabel lblBarraVerde, String root){
            this.imagen = new ImageIcon(root);
            this.icono = new ImageIcon(
                    this.imagen.getImage().getScaledInstance(
                            lblBarraVerde.getWidth(), 
                            lblBarraVerde.getHeight(), 
                            Image.SCALE_DEFAULT)
            );
            lblBarraVerde.setIcon(this.icono);
            this.repaint();
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblBarraVerde;
    private javax.swing.JLabel lblContrasenia;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblFondoAzul;
    private javax.swing.JLabel lblFondoMorado;
    private javax.swing.JLabel lblLogoAreaDeMantenimiento;
    private javax.swing.JLabel lblLogoUtj;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JPanel pnlPrincipalBlanco;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtContresenia;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
