/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

import BackEnd.Usuario;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
/**
 *
 * @author Eduardo Arturo Gutiérrez Hernández
 */
public class NuevoUsuario extends javax.swing.JFrame {
    
    //Objeto para guardar la informacion del usuario nuevo
    Usuario usuario = new Usuario();

    //Declaración de menus para la navegación entre paginas.
    private InicioDeSesion FormRegistrate; 
    
    //Objetos para las imagenes
    private ImageIcon imagen;
    private Icon icono;
    
    public NuevoUsuario() {
        initComponents();
        
        // Obtener el tamaño de la pantalla
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

        // Establecer el tamaño del JFrame al tamaño de la pantalla
        this.setSize(screenSize.width, screenSize.height);

        // Opcional: Establecer la posición del JFrame en la esquina superior izquierda
        this.setLocation(0, 0);
        
        txtId.setText(String.valueOf(usuario.obtenerSiguienteId()));
        
        //Ajustando el tamaño de las imagenes
        this.setLocationRelativeTo(this);
        this.pintarImagen(this.lblBarraVerde, "src/Imagenes/verdeUtj.png");
        this.pintarImagen(lblFondoAzul, "src/Imagenes/verdeUtj_1.png");
        this.pintarImagen(lblFondoMorado, "src/Imagenes/fondoMorado.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblBarraVerde = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnLoggeate = new javax.swing.JButton();
        txtContrasenia = new javax.swing.JTextField();
        lblContrasenia = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        btnGuardar1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblNombre1 = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JTextField();
        lblFondoAzul = new javax.swing.JLabel();
        lblFondoMorado = new javax.swing.JLabel();
        lblLogoAreaDeMantenimiento = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1970, 968));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 72)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registrate");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 180, -1, -1));

        lblBarraVerde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verdeUtj.png"))); // NOI18N
        jPanel1.add(lblBarraVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1970, 130));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoUTJ.png"))); // NOI18N
        jPanel1.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 10, -1, -1));

        btnVolver.setBackground(new java.awt.Color(255, 255, 255));
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(1690, 870, 121, 98));

        btnLoggeate.setBackground(new java.awt.Color(255, 255, 255));
        btnLoggeate.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        btnLoggeate.setForeground(new java.awt.Color(0, 0, 51));
        btnLoggeate.setText("Loggeate");
        btnLoggeate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoggeateActionPerformed(evt);
            }
        });
        jPanel1.add(btnLoggeate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 730, 270, 80));

        txtContrasenia.setBackground(new java.awt.Color(255, 255, 255));
        txtContrasenia.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        txtContrasenia.setForeground(new java.awt.Color(0, 0, 51));
        jPanel1.add(txtContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 630, 470, -1));

        lblContrasenia.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        lblContrasenia.setForeground(new java.awt.Color(0, 0, 51));
        lblContrasenia.setText("Contraseña:");
        jPanel1.add(lblContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 636, -1, -1));

        txtCorreo.setBackground(new java.awt.Color(255, 255, 255));
        txtCorreo.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(0, 0, 51));
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 570, 470, -1));

        lblCorreo.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(0, 0, 51));
        lblCorreo.setText("Correo:");
        jPanel1.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 577, -1, -1));

        txtApellidos.setBackground(new java.awt.Color(255, 255, 255));
        txtApellidos.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        txtApellidos.setForeground(new java.awt.Color(0, 0, 51));
        jPanel1.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 510, 470, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("Apellidos:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 517, -1, -1));

        txtId.setBackground(new java.awt.Color(255, 255, 255));
        txtId.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        txtId.setForeground(new java.awt.Color(0, 0, 51));
        txtId.setEnabled(false);
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 390, 470, -1));

        lblNombre.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(0, 0, 51));
        lblNombre.setText("Id:");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(746, 396, -1, -1));

        btnGuardar1.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardar1.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        btnGuardar1.setForeground(new java.awt.Color(0, 0, 51));
        btnGuardar1.setText("Crear cuenta");
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 730, 270, 80));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1970, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 142, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 144, 1970, 142));

        lblNombre1.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        lblNombre1.setForeground(new java.awt.Color(0, 0, 51));
        lblNombre1.setText("Nombre:");
        jPanel1.add(lblNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 456, -1, -1));

        txtNombre1.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre1.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        txtNombre1.setForeground(new java.awt.Color(0, 0, 51));
        jPanel1.add(txtNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 450, 470, -1));

        lblFondoAzul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/azulfondo.png"))); // NOI18N
        lblFondoAzul.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        jPanel1.add(lblFondoAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 970, 490));

        lblFondoMorado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoMorado.png"))); // NOI18N
        lblFondoMorado.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        jPanel1.add(lblFondoMorado, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 1010, 530));

        lblLogoAreaDeMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/area-restringida (1).png"))); // NOI18N
        jPanel1.add(lblLogoAreaDeMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1016, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        dispose();
        FormRegistrate = new InicioDeSesion();
        FormRegistrate.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnLoggeateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoggeateActionPerformed
        dispose();
        FormRegistrate = new InicioDeSesion();
        FormRegistrate.setVisible(true);
    }//GEN-LAST:event_btnLoggeateActionPerformed

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed
        usuario.setId(Integer.parseInt(txtId.getText()));
        usuario.setNombre(txtNombre1.getText());
        usuario.setApellidos(txtApellidos.getText());
        usuario.setCorreo(txtCorreo.getText());
        usuario.setContrasenia(txtContrasenia.getText());
        
        if((!txtId.getText().equals("")&&
            !txtApellidos.getText().equals("")&&
            !txtCorreo.getText().equals("")&&
            !txtContrasenia.getText().equals(""))){
        JOptionPane.showMessageDialog(null, "Información guardada con exito");
        txtId.setText(String.valueOf(usuario.getId()+1));
        txtNombre1.setText("");
        txtApellidos.setText("");
        txtCorreo.setText("");
        txtContrasenia.setText("");
        usuario.GuardarUsuario();
        }else{
            JOptionPane.showMessageDialog(null, "Llena todos los campos por favor");
        }
    }//GEN-LAST:event_btnGuardar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoUsuario().setVisible(true);
            }
        });
    }
    
    //Metodo para cambiar de tamaño las imagenes
        private void pintarImagen(JLabel lblBarraVerde, String root){
            this.imagen = new ImageIcon(root);
            this.icono = new ImageIcon(
                    this.imagen.getImage().getScaledInstance(
                            lblBarraVerde.getWidth(), 
                            lblBarraVerde.getHeight(), 
                            Image.SCALE_DEFAULT)
            );
            lblBarraVerde.setIcon(this.icono);
            this.repaint();
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar1;
    private javax.swing.JButton btnLoggeate;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblBarraVerde;
    private javax.swing.JLabel lblContrasenia;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblFondoAzul;
    private javax.swing.JLabel lblFondoMorado;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogoAreaDeMantenimiento;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtContrasenia;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre1;
    // End of variables declaration//GEN-END:variables
}
